# Generated by Django 3.2.13 on 2023-06-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['title'], 'verbose_name': 'Стихия', 'verbose_name_plural': 'Стихии'},
        ),
        migrations.AlterModelOptions(
            name='zodiac',
            options={'ordering': ['title'], 'verbose_name': 'Знак зодиака', 'verbose_name_plural': 'Знаки зодиака'},
        ),
        migrations.RenameField(
            model_name='zodiac',
            old_name='url',
            new_name='slug',
        ),
    ]
