# Generated by Django 3.2.13 on 2023-06-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0002_auto_20230602_0053'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zodiac',
            table='zodiac_table',
        ),
    ]
